#include "__cf_IBC_open_basis_test_SMC_False.h"
#ifndef RTW_HEADER_IBC_open_basis_test_SMC_False_acc_types_h_
#define RTW_HEADER_IBC_open_basis_test_SMC_False_acc_types_h_
#include "rtwtypes.h"
#include "multiword_types.h"
typedef struct P_SampleandHold_IBC_open_basis_test_SMC_False_T_
P_SampleandHold_IBC_open_basis_test_SMC_False_T ; typedef struct
P_IBC_open_basis_test_SMC_False_T_ P_IBC_open_basis_test_SMC_False_T ;
#endif
